version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      ETCD_AUTO_COMPACTION_RETENTION: '1'
      ETCD_QUOTA_BACKEND_BYTES: '4294967296'
    volumes:
      - ./volumes/etcd:/etcd_data
    ports:
      - "2379:2379"
    container_name: milvus-etcd

  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    command: server /minio_data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/minio:/minio_data
    ports:
      - "9000:9000"
    container_name: milvus-minio

  milvus:
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run"]
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./volumes/milvus:/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
      DATA_PATH: /milvus
    depends_on:
      - etcd
      - minio
    container_name: milvus
